bibentry(bibtype = "InProceedings",
         key = "Dhillon+Guan+Kogan:2002",
         author = c(person(given = c("Inderjit", "S."),
                           family = "Dhillon"),
                    person(given = "Yuqiang",
                           family = "Guan"),
                    person(given = "J.",
                           family = "Kogan")),
         booktitle = "2002 IEEE International Conference on Data Mining",
         title = "Iterative Clustering of High Dimensional Text Data Augmented by Local Search",
         year = "2002",
         pages = "131--138",
         doi = "10.1109/ICDM.2002.1183895",
         url = "https://www.cs.utexas.edu/~inderjit/public_papers/iterative_icdm02.pdf")

bibentry(bibtype = "Article",
         key = "Dhillon+Modha:2001",
         title = "Concept Decompositions for Large Sparse Text Data Using Clustering",
         volume = "42",
         .issn = "1573-0565",
         doi = "10.1023/a:1007612920971",
         number = "1--2",
         journal = "Machine Learning",
         publisher = "Springer Science and Business Media LLC",
         author = c(person(given = c("Inderjit", "S."),
                           family = "Dhillon"),
                    person(given = c("Dharmendra", "S."),
                           family = "Modha")),
         year = "2001",
         month = "jan",
         pages = "143--175")

bibentry(bibtype = "Article",
         key = "Krishna+Narasimha_Murty:1999",
         title = "Genetic $K$-means algorithm",
         volume = "29",
         .issn = "1083-4419",
         doi = "10.1109/3477.764879",
         number = "3",
         journal = "IEEE Transactions on Systems, Man and Cybernetics, Part B (Cybernetics)",
         publisher = "Institute of Electrical and Electronics Engineers (IEEE)",
         author = c(person(given = "K.",
                           family = "Krishna"),
                    person(given = "M.",
                           family = "Narasimha Murty")),
         year = "1999",
         month = "jun",
         pages = "433--439")

bibentry(bibtype = "TechReport",
         key = "Karypis:2002",
         author = person(given = "George",
                         family = "Karypis"),
         title = "{CLUTO}: A Clustering Toolkit",
         institution = "Department of Computer Science, University of Minnesota",
         year = "2002",
         number = "02-017",
         url = "https://hdl.handle.net/11299/215521")

bibentry(bibtype = "Article",
         key = "Maitra+Ramler:2010",
         title = "A $k$-mean-directions Algorithm for Fast Clustering of Data on the Sphere",
         volume = "19",
         .issn = "1537-2715",
         doi = "10.1198/jcgs.2009.08155",
         number = "2",
         journal = "Journal of Computational and Graphical Statistics",
         publisher = "Informa UK Limited",
         author = c(person(given = c("Ivan", "P."),
                           family = "Ramler"),
                    person(given = "Ranjan",
                           family = "Maitra")),
         year = "2010",
         month = "jan",
         pages = "377--396")

